import type { AttendanceRecord, AttendanceSettings, Assignment, Experiment, ExtraLecture, Habit, HabitRecord, TimetableEntry } from '@/types';
export type AttendanceStatusLabel = 'SAFE' | 'AT_RISK' | 'BELOW_REQUIRED';
export interface AttendanceSummary { subjectId: string; present: number; absent: number; total: number; percentage: number; requiredPercentage: number; status: AttendanceStatusLabel; neededToReachRequired: number | null; canRecover: boolean; }
export interface OverallAttendanceSummary { present: number; absent: number; total: number; percentage: number; }
export interface AttendanceDateSummary { from: string; to: string; total: number; present: number; absent: number; percentage: number; bySubject: Array<AttendanceSummary>; }
export interface AttendanceService { getRecords(userId:string):Promise<AttendanceRecord[]>; createRecord(userId:string,input:AttendanceRecordInput):Promise<AttendanceRecord>; updateRecord(userId:string,id:string,input:AttendanceRecordInput):Promise<AttendanceRecord>; deleteRecord(userId:string,id:string):Promise<void>; getSettings(userId:string):Promise<AttendanceSettings[]>; setRequiredPercentage(userId:string,subjectId:string,requiredPercentage:number):Promise<AttendanceSettings>; getSummary(userId:string,subjectId:string):Promise<AttendanceSummary>; getOverallSummary(userId:string):Promise<OverallAttendanceSummary>; getDateSummary(userId:string,from:string,to:string):Promise<AttendanceDateSummary>; adjustCount(userId:string,subjectId:string,status:'present'|'absent',delta:1|-1):Promise<AttendanceSummary>; }
export interface AttendanceRecordInput { subjectId:string; date:string; status:'present'|'absent'; lectureTitle?:string; lectureId?:string; }
export interface TimetableService { getEntries(userId:string):Promise<TimetableEntry[]>; getExtraLectures(userId:string):Promise<ExtraLecture[]>; createEntry(userId:string,input:TimetableInput):Promise<TimetableEntry>; updateEntry(userId:string,id:string,input:TimetableInput):Promise<TimetableEntry>; deleteEntry(userId:string,id:string):Promise<void>; createExtraLecture(userId:string,input:ExtraLectureInput):Promise<ExtraLecture>; updateExtraLecture(userId:string,id:string,input:ExtraLectureInput):Promise<ExtraLecture>; deleteExtraLecture(userId:string,id:string):Promise<void>; getToday(userId:string,date?:Date):Promise<Array<TimetableEntry|ExtraLecture>>; }
export interface TimetableInput { subjectId?:string; title:string; dayOfWeek:number; startTime:string; endTime:string; room?:string; professor?:string; batch?:string; type:'LECTURE'|'PRACTICAL'|'EXTRA'; }
export interface ExtraLectureInput { subjectId:string; title:string; date:string; startTime:string; endTime:string; room?:string; professor?:string; batch?:string; }
export interface AssignmentService { getAssignments(userId:string):Promise<Assignment[]>; createAssignment(userId:string,input:AssignmentInput):Promise<Assignment>; updateAssignment(userId:string,id:string,input:AssignmentInput):Promise<Assignment>; deleteAssignment(userId:string,id:string):Promise<void>; setStatus(userId:string,id:string,status:Assignment['status']):Promise<Assignment>; getSummary(userId:string,now?:Date):Promise<AssignmentSummary>; }
export interface AssignmentInput { subjectId:string; title:string; description?:string; dueDate:string; notes?:string; status?:Assignment['status']; }
export interface AssignmentSummary { total:number; pending:number; inProgress:number; completed:number; dueSoon:number; overdue:number; }
export interface ExperimentService { getExperiments(userId:string):Promise<Experiment[]>; createExperiment(userId:string,input:ExperimentInput):Promise<Experiment>; updateExperiment(userId:string,id:string,input:ExperimentInput):Promise<Experiment>; deleteExperiment(userId:string,id:string):Promise<void>; getProgress(userId:string):Promise<ExperimentProgress>; }
export interface ExperimentInput { subjectId:string; experimentNumber:number; name:string; description?:string; dueDate?:string; completionStatus?:Experiment['completionStatus']; checkedStatus?:Experiment['checkedStatus']; }
export interface ExperimentProgress { total:number; completed:number; checked:number; completionPercentage:number; checkedPercentage:number; }
export interface HabitService { getHabits(userId:string):Promise<Habit[]>; createHabit(userId:string,input:HabitInput):Promise<Habit>; updateHabit(userId:string,id:string,input:HabitInput):Promise<Habit>; deleteHabit(userId:string,id:string):Promise<void>; setActive(userId:string,id:string,active:boolean):Promise<Habit>; getRecords(userId:string,from?:string,to?:string):Promise<HabitRecord[]>; toggleToday(userId:string,habitId:string,date?:Date):Promise<HabitRecord>; getToday(userId:string,date?:Date):Promise<Array<{habit:Habit;record:HabitRecord|null;streak:number}>>; getStreak(userId:string,habitId:string,date?:Date):Promise<number>; }
export interface HabitInput { name:string; description?:string; frequency:'DAILY'|'WEEKLY'; targetDays?:number[]; active?:boolean; }
