import { useCallback, useEffect, useState } from 'react';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { AcademicPageHeader } from '@/features/academics/components/AcademicPageHeader';
import { AcademicModal } from '@/features/academics/components/AcademicModal';
import { ConfirmDialog } from '@/features/academics/components/ConfirmDialog';
import { remindersService } from '../services/api';
import type { Reminder } from '@/types';
export function RemindersPage() {
  const [items,setItems]=useState<Reminder[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Reminder|null>(null); const [removeTarget,setRemoveTarget]=useState<Reminder|null>(null); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setItems(await remindersService.list())}catch(e){setError(e instanceof Error?e.message:'Unable to load reminders.')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);
  const save=async(v:{title:string;scheduledFor:string;completed:boolean})=>{setBusy(true);setError(null);try{if(editing)await remindersService.update(editing.id,v);else await remindersService.create(v as Omit<Reminder,'id'|'userId'>);setOpen(false);setEditing(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save reminder.')}finally{setBusy(false)}};
  const remove=async()=>{if(!removeTarget)return;setBusy(true);try{await remindersService.remove(removeTarget.id);setRemoveTarget(null);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to delete reminder.')}finally{setBusy(false)}};
  return <div className="phase10-page"><AcademicPageHeader eyebrow="System" title="Reminders" description="Keep personal study and academic reminders in one place." action={<Button onClick={()=>{setEditing(null);setOpen(true)}}>Add reminder</Button>}/>{error&&<Card><p className="phase10-error" role="alert">{error}</p></Card>}{loading?<Card><p>Loading reminders…</p></Card>:items.length===0?<Card><p>No reminders yet.</p><Button onClick={()=>setOpen(true)}>Add reminder</Button></Card>:<div className="phase10-report-grid">{items.map(r=><Card key={r.id}><h3>{r.title}</h3><p>{new Date(r.scheduledFor).toLocaleString()}</p><strong>{r.completed?'Completed':'Pending'}</strong><div className="phase8-inline-actions"><Button size="sm" variant="ghost" onClick={()=>{setEditing(r);setOpen(true)}}>Edit</Button><Button size="sm" variant="ghost" onClick={()=>setRemoveTarget(r)}>Delete</Button></div></Card>)}</div>}<ReminderForm open={open} initial={editing} busy={busy} error={error} onClose={()=>{if(!busy)setOpen(false)}} onSubmit={save}/><ConfirmDialog open={Boolean(removeTarget)} title="Delete reminder?" message="This reminder will be permanently removed." busy={busy} onCancel={()=>setRemoveTarget(null)} onConfirm={()=>void remove()}/></div>
}
function ReminderForm({open,initial,busy,error,onClose,onSubmit}:{open:boolean;initial:Reminder|null;busy:boolean;error:string|null;onClose:()=>void;onSubmit:(v:{title:string;scheduledFor:string;completed:boolean})=>void}){const [v,setV]=useState({title:initial?.title??'',scheduledFor:initial?.scheduledFor?initial.scheduledFor.slice(0,16):'',completed:initial?.completed??false});useEffect(()=>setV({title:initial?.title??'',scheduledFor:initial?.scheduledFor?initial.scheduledFor.slice(0,16):'',completed:initial?.completed??false}),[initial,open]);return <AcademicModal open={open} title={initial?'Edit reminder':'Add reminder'} description="Choose a date and time for the reminder." onClose={onClose}><form className="academic-form" onSubmit={e=>{e.preventDefault();onSubmit(v)}}><Input label="Title" value={v.title} onChange={e=>setV({...v,title:e.target.value})} required/><Input label="Date & time" type="datetime-local" value={v.scheduledFor} onChange={e=>setV({...v,scheduledFor:e.target.value})} required/><label><input type="checkbox" checked={v.completed} onChange={e=>setV({...v,completed:e.target.checked})}/> Completed</label>{error&&<p className="phase10-error" role="alert">{error}</p>}<div className="academic-form__actions"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy?'Saving…':'Save reminder'}</Button></div></form></AcademicModal>}
