import type { ID, StudySession } from '@/types';
import { createUserDoc, deleteUserDoc, getUserDoc, listUserDocs, updateUserDoc, setUserDoc } from '@/services/firebase/db';
import type { ActiveTimerState, StudyService, StudySessionInput, StudySummary, SubjectStudyTime } from '@/features/productivity/types/productivity';
import { getElapsedSeconds, isSessionInCurrentWeek, isSessionOnLocalDay } from '@/features/productivity/utils/time';
import { academicService } from '@/features/academics/services/academicService';

const now=()=>new Date().toISOString();
const activeName='runtime';
function assertTarget(input:StudySessionInput){if(input.targetType==='SUBJECT'&&!input.subjectId)throw new Error('Select a subject before starting study.');if(input.targetType==='MODULE'&&(!input.subjectId||!input.moduleId))throw new Error('Select a subject and module before starting study.');if(input.targetType==='TOPIC'&&(!input.subjectId||!input.moduleId||!input.topicId))throw new Error('Select a subject, module and topic before starting study.');if(input.targetType==='EXTRA_TASK'&&!input.extraTaskLabel?.trim())throw new Error('Enter an extra learning task name.');}
async function validateTarget(uid:string,input:StudySessionInput){assertTarget(input);if(input.targetType==='EXTRA_TASK')return;const s=await academicService.getSubject(uid,input.subjectId!);if(!s)throw new Error('The selected subject is unavailable.');if(input.targetType==='SUBJECT')return;const m=await academicService.getModule(uid,input.moduleId!);if(!m||m.subjectId!==s.id)throw new Error('The selected module does not belong to this subject.');if(input.targetType==='MODULE')return;const ts=await academicService.getTopics(uid,m.id);if(!ts.some(t=>t.id===input.topicId))throw new Error('The selected topic does not belong to this module.');}
async function active(uid:string){return getUserDoc<ActiveTimerState>(uid,activeName,'activeTimer');}
async function clearActive(uid:string){try{await deleteUserDoc(uid,activeName,'activeTimer')}catch{}}
async function setActive(uid:string,value:ActiveTimerState){await setUserDoc<ActiveTimerState>(uid,activeName,'activeTimer',value);}
async function sessionOrThrow(uid:string,id:string){const s=await getUserDoc<StudySession>(uid,'studySessions',id);if(!s)throw new Error('Study session not found.');return s;}
function materialize(s:StudySession,a:ActiveTimerState|null){return a&&a.sessionId===s.id&&s.status==='RUNNING'?{...s,durationSeconds:getElapsedSeconds(a.accumulatedSeconds,a.lastStartedAt)}:s;}

export function createApiStudyService():StudyService{return {
  async startSession(uid,input){await validateTarget(uid,input);const existing=await active(uid);if(existing)throw new Error('Finish or pause the current study session before starting another.');const t=now();const session=await createUserDoc<StudySession>(uid,'studySessions',{userId:uid,...input,startedAt:t,durationSeconds:0,status:'RUNNING',createdAt:t,updatedAt:t} as Omit<StudySession,'id'>);await setActive(uid,{sessionId:session.id,userId:uid,status:'RUNNING',accumulatedSeconds:0,lastStartedAt:t,updatedAt:t});return session;},
  async pauseSession(uid,id){const s=await sessionOrThrow(uid,id);if(s.status!=='RUNNING')throw new Error('Only a running session can be paused.');const a=await active(uid);const duration=a?.sessionId===id?getElapsedSeconds(a.accumulatedSeconds,a.lastStartedAt):s.durationSeconds;const next=await updateUserDoc<StudySession>(uid,'studySessions',id,{status:'PAUSED',durationSeconds:duration,updatedAt:now()});await setActive(uid,{sessionId:id,userId:uid,status:'PAUSED',accumulatedSeconds:duration,lastStartedAt:null,updatedAt:now()});return next;},
  async resumeSession(uid,id){const s=await sessionOrThrow(uid,id);if(s.status!=='PAUSED')throw new Error('Only a paused session can be resumed.');const existing=await active(uid);if(existing&&existing.sessionId!==id)throw new Error('Another study session is already active.');const t=now();const next=await updateUserDoc<StudySession>(uid,'studySessions',id,{status:'RUNNING',updatedAt:t});await setActive(uid,{sessionId:id,userId:uid,status:'RUNNING',accumulatedSeconds:s.durationSeconds,lastStartedAt:t,updatedAt:t});return next;},
  async completeSession(uid,id,input){const s=await sessionOrThrow(uid,id);const a=await active(uid);const duration=a?.sessionId===id?getElapsedSeconds(a.accumulatedSeconds,a.lastStartedAt):s.durationSeconds;const t=now();const next=await updateUserDoc<StudySession>(uid,'studySessions',id,{...input,status:'COMPLETED',durationSeconds:duration,endedAt:t,updatedAt:t});if(a?.sessionId===id)await clearActive(uid);return next;},
  async cancelSession(uid,id){const s=await sessionOrThrow(uid,id);const a=await active(uid);const duration=a?.sessionId===id?getElapsedSeconds(a.accumulatedSeconds,a.lastStartedAt):s.durationSeconds;const next=await updateUserDoc<StudySession>(uid,'studySessions',id,{status:'CANCELLED',durationSeconds:duration,endedAt:now(),updatedAt:now()});if(a?.sessionId===id)await clearActive(uid);return next;},
  async getActiveSession(uid){const a=await active(uid);return a?materialize(await sessionOrThrow(uid,a.sessionId),a):null;},
  async getActiveTimer(uid){return active(uid);},
  async getElapsedSeconds(uid,id){const s=await sessionOrThrow(uid,id);const a=await active(uid);return a?.sessionId===id?getElapsedSeconds(a.accumulatedSeconds,a.lastStartedAt):s.durationSeconds;},
  async getSessions(uid){const a=await active(uid);return (await listUserDocs<StudySession>(uid,'studySessions')).map(s=>materialize(s,a)).sort((x,y)=>y.startedAt.localeCompare(x.startedAt));},
  async updateSession(uid,id,input){return updateUserDoc<StudySession>(uid,'studySessions',id,{...input,updatedAt:now()});},
  async deleteSession(uid,id){const a=await active(uid);if(a?.sessionId===id)await clearActive(uid);await deleteUserDoc(uid,'studySessions',id);},
  async getSummary(uid,at=new Date()){const sessions=await this.getSessions(uid);const completed=sessions.filter(s=>s.status==='COMPLETED');const total=completed.reduce((n,s)=>n+s.durationSeconds,0);const today=completed.filter(s=>isSessionOnLocalDay(s,at)).reduce((n,s)=>n+s.durationSeconds,0);const week=completed.filter(s=>isSessionInCurrentWeek(s,at)).reduce((n,s)=>n+s.durationSeconds,0);return {todaySeconds:today,weekSeconds:week,totalSeconds:total,completedSessions:completed.length,averageSessionSeconds:completed.length?Math.round(total/completed.length):0};},
  async getStudyTimeBySubject(uid){const sessions=await this.getSessions(uid);const map=new Map<ID,number>();sessions.filter(s=>s.status==='COMPLETED'&&s.subjectId).forEach(s=>map.set(s.subjectId!, (map.get(s.subjectId!)??0)+s.durationSeconds));return [...map.entries()].map(([subjectId,seconds])=>({subjectId,seconds}));},
};}
