import type { Experiment } from '@/types';
import { academicService } from '@/features/academics/services/academicService';
import type { ExperimentInput, ExperimentService } from '../types';
import { calculateExperimentProgress } from '../utils/calculations';
import { makeId, now, persistUserStore, userStore } from './storage';
const seeded=new Set<string>();
async function ensureSeed(userId:string){if(seeded.has(userId))return;const subjects=await academicService.getSubjects(userId);const store=userStore(userId);if(store.experiments.length===0&&subjects.length){const c=now();const experiments:Experiment[]=[];for(let i=0;i<8;i++){const subject=subjects[i%subjects.length];experiments.push({id:makeId('experiment'),userId,subjectId:subject.id,experimentNumber:i+1,name:`Practical Experiment ${i+1}`,description:'Sample practical work.',completionStatus:i<5?'COMPLETED':'PENDING',checkedStatus:i<3?'CHECKED':'NOT_CHECKED',completedAt:i<5?c:undefined,checkedAt:i<3?c:undefined,createdAt:c,updatedAt:c});}persistUserStore(userId,{...store,experiments});}seeded.add(userId);}
async function validateSubject(userId:string,id:string){const subjects=await academicService.getSubjects(userId);if(!subjects.some(s=>s.id===id))throw new Error('Subject not found.');}
function validate(input:ExperimentInput){if(!input.name.trim())throw new Error('Experiment name is required.');if(!Number.isInteger(input.experimentNumber)||input.experimentNumber<1)throw new Error('Experiment number must be a positive whole number.');}
export function createMockExperimentService():ExperimentService{return {async getExperiments(userId){await ensureSeed(userId);return userStore(userId).experiments.sort((a,b)=>a.experimentNumber-b.experimentNumber);},async createExperiment(userId,input){await ensureSeed(userId);validate(input);await validateSubject(userId,input.subjectId);const c=now();const completion=input.completionStatus??'PENDING';const checked=input.checkedStatus??'NOT_CHECKED';if(checked==='CHECKED'&&completion!=='COMPLETED')throw new Error('An experiment must be completed before it can be checked.');const e={id:makeId('experiment'),userId,subjectId:input.subjectId,experimentNumber:input.experimentNumber,name:input.name.trim(),description:input.description?.trim()||undefined,dueDate:input.dueDate,completionStatus:completion,checkedStatus:checked,completedAt:completion==='COMPLETED'?c:undefined,checkedAt:checked==='CHECKED'?c:undefined,createdAt:c,updatedAt:c};const store=userStore(userId);persistUserStore(userId,{...store,experiments:[...store.experiments,e]});return e;},async updateExperiment(userId,id,input){await ensureSeed(userId);validate(input);await validateSubject(userId,input.subjectId);const store=userStore(userId);const i=store.experiments.findIndex(x=>x.id===id);if(i<0)throw new Error('Experiment not found.');const old=store.experiments[i];const completion=input.completionStatus??old.completionStatus;const checked=input.checkedStatus??old.checkedStatus;if(checked==='CHECKED'&&completion!=='COMPLETED')throw new Error('An experiment must be completed before it can be checked.');const e={...old,...input,name:input.name.trim(),description:input.description?.trim()||undefined,completionStatus:completion,checkedStatus:checked,completedAt:completion==='COMPLETED'?(old.completedAt??now()):undefined,checkedAt:checked==='CHECKED'?(old.checkedAt??now()):undefined,updatedAt:now()};store.experiments[i]=e;persistUserStore(userId,store);return e;},async deleteExperiment(userId,id){await ensureSeed(userId);const store=userStore(userId);if(!store.experiments.some(x=>x.id===id))throw new Error('Experiment not found.');persistUserStore(userId,{...store,experiments:store.experiments.filter(x=>x.id!==id)});},async getProgress(userId){await ensureSeed(userId);return calculateExperimentProgress(userStore(userId).experiments);}}}
