import type { Assignment } from '@/types';
import { academicService } from '@/features/academics/services/academicService';
import type { AssignmentInput, AssignmentService } from '../types';
import { calculateAssignmentSummary } from '../utils/calculations';
import { makeId, now, persistUserStore, userStore } from './storage';
const seeded=new Set<string>();
async function ensureSeed(userId:string){if(seeded.has(userId))return;const subjects=await academicService.getSubjects(userId);const store=userStore(userId);if(store.assignments.length===0&&subjects.length){const c=now();const dates=[-1,0,2,7];const assignments:Assignment[]=subjects.slice(0,4).map((s,i)=>{const d=new Date();d.setDate(d.getDate()+dates[i]);d.setHours(17,0,0,0);return{id:makeId('assignment'),userId,subjectId:s.id,title:['JDBC worksheet','SQL query practice','Logic circuit report','Responsive page task'][i],description:'Sample Phase 8 assignment.',dueDate:d.toISOString(),status:i===0?'PENDING':i===1?'IN_PROGRESS':'COMPLETED',completedAt:i>=2?c:undefined,createdAt:c,updatedAt:c};});persistUserStore(userId,{...store,assignments});}seeded.add(userId);}
async function validateSubject(userId:string,id:string){const subjects=await academicService.getSubjects(userId);if(!subjects.some(s=>s.id===id))throw new Error('Subject not found.');}
function validate(input:AssignmentInput){if(!input.title.trim())throw new Error('Assignment title is required.');if(!input.dueDate||Number.isNaN(new Date(input.dueDate).getTime()))throw new Error('A valid due date is required.');}
export function createMockAssignmentService():AssignmentService{return {async getAssignments(userId){await ensureSeed(userId);return userStore(userId).assignments.sort((a,b)=>new Date(a.dueDate).getTime()-new Date(b.dueDate).getTime());},async createAssignment(userId,input){await ensureSeed(userId);validate(input);await validateSubject(userId,input.subjectId);const c=now();const status=input.status??'PENDING';const a={id:makeId('assignment'),userId,subjectId:input.subjectId,title:input.title.trim(),description:input.description?.trim()||undefined,dueDate:new Date(input.dueDate).toISOString(),status,notes:input.notes?.trim()||undefined,completedAt:status==='COMPLETED'?c:undefined,createdAt:c,updatedAt:c};const store=userStore(userId);persistUserStore(userId,{...store,assignments:[...store.assignments,a]});return a;},async updateAssignment(userId,id,input){await ensureSeed(userId);validate(input);await validateSubject(userId,input.subjectId);const store=userStore(userId);const i=store.assignments.findIndex(x=>x.id===id);if(i<0)throw new Error('Assignment not found.');const old=store.assignments[i];const status=input.status??old.status;const a={...old,...input,subjectId:input.subjectId,title:input.title.trim(),description:input.description?.trim()||undefined,dueDate:new Date(input.dueDate).toISOString(),notes:input.notes?.trim()||undefined,status,completedAt:status==='COMPLETED'?(old.completedAt??now()):undefined,updatedAt:now()};store.assignments[i]=a;persistUserStore(userId,store);return a;},async deleteAssignment(userId,id){await ensureSeed(userId);const store=userStore(userId);if(!store.assignments.some(x=>x.id===id))throw new Error('Assignment not found.');persistUserStore(userId,{...store,assignments:store.assignments.filter(x=>x.id!==id)});},async setStatus(userId,id,status){await ensureSeed(userId);const store=userStore(userId);const i=store.assignments.findIndex(x=>x.id===id);if(i<0)throw new Error('Assignment not found.');const a={...store.assignments[i],status,completedAt:status==='COMPLETED'?(store.assignments[i].completedAt??now()):undefined,updatedAt:now()};store.assignments[i]=a;persistUserStore(userId,store);return a;},async getSummary(userId,date){await ensureSeed(userId);return calculateAssignmentSummary(userStore(userId).assignments,date);}}}
