export const routePaths = {
  home: '/',
  designSystem: '/design-system',
  dashboard: '/dashboard',
  academics: '/academics',
  subjects: '/academics/subjects',
  subjectDetail: (subjectId: string) => `/academics/subjects/${encodeURIComponent(subjectId)}`,
  moduleDetail: (subjectId: string, moduleId: string) => `/academics/subjects/${encodeURIComponent(subjectId)}/modules/${encodeURIComponent(moduleId)}`,
  modules: '/academics/modules',
  topics: '/academics/topics',
  assignments: '/academics/assignments',
  experiments: '/academics/experiments',
  projects: '/academics/projects',
  productivity: '/productivity',
  study: '/productivity/study',
  stopwatch: '/productivity/stopwatch',
  revision: '/productivity/revision',
  habits: '/productivity/habits',
  attendance: '/attendance',
  timetable: '/timetable',
  reports: '/reports',
  analytics: '/analytics',
  reminders: '/reminders',
  settings: '/settings',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
} as const;
