const base = (process.env.API_BASE_URL || 'http://localhost:3000/api').replace(/\/$/, '');
let cookie = '';
async function request(path, options = {}, expected = 200) {
  const headers = new Headers(options.headers);
  headers.set('Accept', 'application/json');
  if (options.body && !headers.has('Content-Type')) headers.set('Content-Type', 'application/json');
  if (cookie) headers.set('Cookie', cookie);
  const response = await fetch(`${base}${path}`, { ...options, headers });
  const setCookies = response.headers.getSetCookie?.() ?? [];
  if (setCookies.length) cookie = setCookies.map(value => value.split(';', 1)[0]).join('; ');
  let payload = null;
  const contentType = response.headers.get('content-type') || '';
  if (contentType.includes('application/json')) payload = await response.json();
  if (response.status !== expected) throw new Error(`${options.method || 'GET'} ${path}: expected ${expected}, got ${response.status} ${JSON.stringify(payload)}`);
  if (payload && payload.success === false) throw new Error(`${options.method || 'GET'} ${path}: ${payload.error?.message || 'API error'}`);
  return payload?.data;
}
const post = (path, body, expected = 201) => request(path, { method: 'POST', body: JSON.stringify(body) }, expected);
const patch = (path, body) => request(path, { method: 'PATCH', body: JSON.stringify(body) });

const email = `smoke-${Date.now()}@syllora.local`;
await request('/health');
await post('/auth/signup', { nickname: 'Local Smoke', email, password: 'LocalSmoke123!', confirmPassword: 'LocalSmoke123!' });
await request('/auth/me');
await request('/auth/session', { method: 'POST' });
await request('/auth/logout', { method: 'POST' }, 204);
await post('/auth/login', { email, password: 'LocalSmoke123!' }, 200);
await request('/auth/me');
await request('/dashboard');
const subject = await post('/subjects', { name: 'Smoke Subject', code: 'SMOKE' });
const subjectList = await request('/subjects');
if (!subjectList.some(x => x.id === subject.id && x.moduleCount === 0 && x.topicCount === 0 && x.progress === 0)) throw new Error('GET /subjects did not return the required subject summary fields.');
const module = await post(`/subjects/${subject.id}/modules`, { name: 'Smoke Module' });
const topic = await post(`/modules/${module.id}/topics`, { name: 'Smoke Topic' });
await patch(`/topics/${topic.id}/status`, { status: 'completed' });
const assignment = await post('/assignments', { subjectId: subject.id, title: 'Smoke Assignment', dueDate: new Date(Date.now() + 86400000).toISOString(), status: 'PENDING' });
await patch(`/assignments/${assignment.id}/status`, { status: 'COMPLETED' });
const experiment = await post('/experiments', { subjectId: subject.id, experimentNumber: 999, name: 'Smoke Experiment', dueDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10) });
await patch(`/experiments/${experiment.id}`, { subjectId: subject.id, experimentNumber: 999, name: 'Smoke Experiment', dueDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10), completionStatus: 'COMPLETED', checkedStatus: 'CHECKED' });
const habit = await post('/habits', { name: 'Smoke Habit', frequency: 'DAILY', targetDays: [0,1,2,3,4,5,6], active: true });
await post(`/habits/${habit.id}/today/toggle`, {}, 200);
const attendance = await post('/attendance', { subjectId: subject.id, date: new Date().toISOString().slice(0, 10), status: 'present', lectureTitle: 'Smoke Lecture' });
await patch(`/attendance/${attendance.id}`, { subjectId: subject.id, date: new Date().toISOString().slice(0, 10), status: 'present', lectureTitle: 'Smoke Lecture Updated' });
await post('/timetable', { subjectId: subject.id, title: 'Smoke Lecture', dayOfWeek: new Date().getDay(), startTime: '09:00', endTime: '10:00', type: 'LECTURE' });
const study = await post('/study-sessions', { subjectId: subject.id, targetType: 'SUBJECT' });
await post(`/study-sessions/${study.id}/pause`, {} ,200);
await post(`/study-sessions/${study.id}/complete`, {}, 200);
await post('/revisions', { subjectId: subject.id, revisedAt: new Date().toISOString(), notes: 'Smoke revision' });
await post('/projects', { subjectId: subject.id, name: 'Smoke Project', dueDate: new Date(Date.now() + 86400000).toISOString().slice(0, 10) });
await post('/reminders', { title: 'Smoke Reminder', scheduledFor: new Date(Date.now() + 86400000).toISOString(), completed: false });
await request('/reports');
await request('/reports/attendance.csv');
await request('/notifications');
await request('/notification-preferences');
console.log(`Local API smoke test: PASS (${email})`);
