import type { AttendanceRecord, Assignment, Experiment, HabitRecord } from '@/types';
import type { AttendanceStatusLabel, AttendanceSummary, OverallAttendanceSummary, AssignmentSummary, ExperimentProgress } from '../types';
export function calculateAttendancePercentage(present:number,total:number):number { return total<=0?0:Number(((present/total)*100).toFixed(2)); }
export function calculateAttendanceStatus(percentage:number,required:number):AttendanceStatusLabel { const risk=Math.max(5,Math.min(10,required*0.1)); if(percentage<required)return 'BELOW_REQUIRED'; if(percentage<required+risk)return 'AT_RISK'; return 'SAFE'; }
export function calculateRequiredAttendanceProjection(present:number,absent:number,required:number):{needed:number|null;canRecover:boolean}{ const total=present+absent; if(required<=0)return {needed:0,canRecover:true}; if(required>=100)return {needed:null,canRecover:false}; if(calculateAttendancePercentage(present,total)>=required)return {needed:0,canRecover:true}; const needed=Math.ceil((required*total/100-present)/((100-required)/100)); return {needed:Math.max(0,needed),canRecover:true}; }
export function calculateAttendanceSummary(subjectId:string,records:AttendanceRecord[],required=75):AttendanceSummary { const subject=records.filter(r=>r.subjectId===subjectId); const present=subject.filter(r=>r.status==='present').length; const absent=subject.length-present; const percentage=calculateAttendancePercentage(present,subject.length); const projection=calculateRequiredAttendanceProjection(present,absent,required); return {subjectId,present,absent,total:subject.length,percentage,requiredPercentage:required,status:calculateAttendanceStatus(percentage,required),neededToReachRequired:projection.needed,canRecover:projection.canRecover}; }
export function calculateOverallAttendance(records:AttendanceRecord[]):OverallAttendanceSummary { const present=records.filter(r=>r.status==='present').length; const absent=records.length-present; return {present,absent,total:records.length,percentage:calculateAttendancePercentage(present,records.length)}; }
export function calculateAssignmentSummary(assignments:Assignment[],now=new Date()):AssignmentSummary { const today=new Date(now); today.setHours(0,0,0,0); const soon=new Date(today); soon.setDate(soon.getDate()+2); const summary={total:assignments.length,pending:0,inProgress:0,completed:0,dueSoon:0,overdue:0}; assignments.forEach(a=>{if(a.status==='COMPLETED')summary.completed++;else if(a.status==='IN_PROGRESS')summary.inProgress++;else summary.pending++; if(a.status!=='COMPLETED'){const due=new Date(a.dueDate); if(due<today)summary.overdue++; else if(due<=new Date(soon.getTime()+86_399_999))summary.dueSoon++;}}); return summary; }
export function assignmentDueState(assignment:Assignment,now=new Date()):'COMPLETED'|'OVERDUE'|'DUE_TODAY'|'DUE_SOON'|'UPCOMING'{ if(assignment.status==='COMPLETED')return 'COMPLETED'; const diff=daysBetweenLocal(new Date(assignment.dueDate),now); if(diff<0)return 'OVERDUE'; if(diff===0)return 'DUE_TODAY'; if(diff<=2)return 'DUE_SOON'; return 'UPCOMING'; }
function daysBetweenLocal(a:Date,b:Date){ const aa=new Date(a); const bb=new Date(b); aa.setHours(0,0,0,0); bb.setHours(0,0,0,0); return Math.round((aa.getTime()-bb.getTime())/86_400_000); }
export function calculateExperimentProgress(experiments:Experiment[]):ExperimentProgress { const total=experiments.length; const completed=experiments.filter(e=>e.completionStatus==='COMPLETED').length; const checked=experiments.filter(e=>e.checkedStatus==='CHECKED').length; return {total,completed,checked,completionPercentage:total?Number((completed/total*100).toFixed(1)):0,checkedPercentage:total?Number((checked/total*100).toFixed(1)):0}; }
export function calculateHabitStreak(records:HabitRecord[],date=new Date()):number { const completed=new Set(records.filter(r=>r.completed).map(r=>r.date)); const cursor=new Date(date); cursor.setHours(0,0,0,0); let streak=0; while(completed.has(localKey(cursor))){streak++;cursor.setDate(cursor.getDate()-1);} return streak; }
function localKey(date:Date){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
export function calculateHabitCompletion(records:HabitRecord[],date=new Date()):boolean{return records.some(r=>r.date===localKey(date)&&r.completed);}
